version: '2'
services:
  personalaccounting-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/personalAccounting/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=personalAccounting
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
